### ISSUE TITLE
ArgumentError with version 4.0.4

### ISSUE THREAD

**Issue by danielbayerlein** [follmann/middleman-favicon-maker#44]
The `middleman-favicon-maker` update from `v4.0.3` to `v4.0.4` breaks my build. Do you have any idea?

**Gemfile**

```diff
source 'https://rubygems.org'

ruby '2.4.1'

gem 'middleman', '~> 4.2.1'
gem 'middleman-livereload', '~> 3.4.6'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-minify-html', '~> 3.4.1'
- gem 'middleman-favicon-maker', '4.0.3'
+ gem 'middleman-favicon-maker', '4.0.4'
gem 'middleman-google-analytics', '~> 3.0.0'
```

**Config**

```ruby
configure :build do
  activate :favicon_maker do |f|
    f.template_dir  = 'source/images'
    f.output_dir  = 'build/images'
    f.icons = {
      '_favicon_template.png' => [
        { icon: "apple-touch-icon.png", size: "180x180" },
        { icon: "favicon.ico", size: "32x32,16x16" }
      ]
    }
  end
end
```

**Log**

```text
/Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/2.4.0/pathname.rb:520:in `relative_path_from': different prefix: "" and "/Users/danielbayerlein/Projects/bienenkind.de/source" (ArgumentError)
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/resource.rb:57:in `initialize'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `new'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `block (2 levels) in manipulate_resource_list'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `map'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `block in manipulate_resource_list'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `manipulate_resource_list'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:309:in `initialize'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/build.rb:63:in `new'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/build.rb:63:in `block in build'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/lib/middleman-cli/build.rb:62:in `build'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:70:in `<top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/bin/middleman:22:in `load'
        from /Users/danielbayerlein/.rbenv/versions/2.4.1/bin/middleman:22:in `<main>'
```

**Comment by danielbayerlein** [comment]
#42

**Comment by follmann** [comment]
v4.0.5 is pushed, please test!

**Comment by danielbayerlein** [comment]
@follmann Thank you! It works 👷
